owner: maxirobledo 
repo: upptime 

sites:
  - name: Hello world
    url: https://example.snappypreview.com/
  
assignees: maxirobledo

status-website:
 # cname: status.snappypreview.com
  baseUrl: /upptime
  name: Snappy Status
  theme: light

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All systems are operational
  footer: Powered by Upptime  
